/* tslint:disable */
/* eslint-disable */
/**
 * CeilR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface CheckFeature200Response
 */
export interface CheckFeature200Response {
    /**
     * 
     * @type {boolean}
     * @memberof CheckFeature200Response
     */
    'allowed'?: boolean;
}
/**
 * 
 * @export
 * @interface CheckFeatureRequest
 */
export interface CheckFeatureRequest {
    /**
     * 
     * @type {string}
     * @memberof CheckFeatureRequest
     */
    'featureName'?: string;
}
/**
 * 
 * @export
 * @interface GetUserEntitlements200Response
 */
export interface GetUserEntitlements200Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof GetUserEntitlements200Response
     */
    'entitlements'?: Array<string>;
}
/**
 * 
 * @export
 * @interface TrackUsageRequest
 */
export interface TrackUsageRequest {
    /**
     * 
     * @type {string}
     * @memberof TrackUsageRequest
     */
    'featureName'?: string;
    /**
     * 
     * @type {number}
     * @memberof TrackUsageRequest
     */
    'count'?: number;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Check if a feature is enabled
         * @param {CheckFeatureRequest} checkFeatureRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkFeature: async (checkFeatureRequest: CheckFeatureRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'checkFeatureRequest' is not null or undefined
            assertParamExists('checkFeature', 'checkFeatureRequest', checkFeatureRequest)
            const localVarPath = `/check-feature`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(checkFeatureRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get user entitlements
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserEntitlements: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user-entitlements`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Track feature usage
         * @param {TrackUsageRequest} trackUsageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        trackUsage: async (trackUsageRequest: TrackUsageRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'trackUsageRequest' is not null or undefined
            assertParamExists('trackUsage', 'trackUsageRequest', trackUsageRequest)
            const localVarPath = `/track-usage`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(trackUsageRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Check if a feature is enabled
         * @param {CheckFeatureRequest} checkFeatureRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async checkFeature(checkFeatureRequest: CheckFeatureRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CheckFeature200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.checkFeature(checkFeatureRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.checkFeature']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get user entitlements
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserEntitlements(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserEntitlements200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserEntitlements(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getUserEntitlements']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Track feature usage
         * @param {TrackUsageRequest} trackUsageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async trackUsage(trackUsageRequest: TrackUsageRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.trackUsage(trackUsageRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.trackUsage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Check if a feature is enabled
         * @param {CheckFeatureRequest} checkFeatureRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkFeature(checkFeatureRequest: CheckFeatureRequest, options?: RawAxiosRequestConfig): AxiosPromise<CheckFeature200Response> {
            return localVarFp.checkFeature(checkFeatureRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get user entitlements
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserEntitlements(options?: RawAxiosRequestConfig): AxiosPromise<GetUserEntitlements200Response> {
            return localVarFp.getUserEntitlements(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Track feature usage
         * @param {TrackUsageRequest} trackUsageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        trackUsage(trackUsageRequest: TrackUsageRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.trackUsage(trackUsageRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Check if a feature is enabled
     * @param {CheckFeatureRequest} checkFeatureRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public checkFeature(checkFeatureRequest: CheckFeatureRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).checkFeature(checkFeatureRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get user entitlements
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getUserEntitlements(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getUserEntitlements(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Track feature usage
     * @param {TrackUsageRequest} trackUsageRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public trackUsage(trackUsageRequest: TrackUsageRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).trackUsage(trackUsageRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



